from pathlib import Path
import json, shutil

ROOT=Path('/mnt/data/raildock-web')
DOCS=ROOT/'docs'
DOCS.mkdir(exist_ok=True)

package={
  "name":"raildock-docs","private":True,"version":"0.1.0","type":"module",
  "scripts":{"dev":"vite --host 0.0.0.0","build":"vite build","preview":"vite preview --host 0.0.0.0"},
  "dependencies":{"@holocron.so/vite":"0.32.0","react":"^19.2.0","react-dom":"^19.2.0","vite":"^7.2.4"}
}
(DOCS/'package.json').write_text(json.dumps(package,indent=2)+"\n")
(DOCS/'vite.config.ts').write_text("""import { defineConfig } from 'vite'\nimport { holocron } from '@holocron.so/vite'\n\nexport default defineConfig({\n  base: '/docs/',\n  plugins: [holocron()],\n})\n""")

public=DOCS/'public'; public.mkdir(exist_ok=True)
logo='''<svg width="200" height="44" viewBox="0 0 200 44" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="1" y="1" width="42" height="42" rx="12" fill="#131318" stroke="#2A2A33"/><path d="M11 14.5C11 12.567 12.567 11 14.5 11H28.8C31.1196 11 33 12.8804 33 15.2V17.4C33 19.7196 31.1196 21.6 28.8 21.6H17.4V33H14.5C12.567 33 11 31.433 11 29.5V14.5Z" fill="#8B5CF6"/><path d="M20.1 24.1H28.65C31.052 24.1 33 26.048 33 28.45V29.1C33 31.254 31.254 33 29.1 33H20.1V24.1Z" fill="#A78BFA"/><path d="M17.4 16.2H27.2" stroke="#F6F3FF" stroke-width="2.2" stroke-linecap="round"/><text x="55" y="28" fill="#F5F5F7" font-family="Inter,Arial,sans-serif" font-size="20" font-weight="650">RailDock</text></svg>'''
(public/'logo.svg').write_text(logo)
(public/'favicon.svg').write_text(logo.replace('width="200" height="44" viewBox="0 0 200 44"','width="44" height="44" viewBox="0 0 44 44"').split('<text')[0]+'</svg>')

nav={
 "$schema":"https://holocron.so/docs.json",
 "name":"RailDock Docs",
 "description":"Deploy and operate applications and databases on servers you control with RailDock.",
 "colors":{"primary":"#8B5CF6","light":"#8B5CF6","dark":"#A78BFA"},
 "logo":{"light":"/logo.svg","dark":"/logo.svg"},
 "favicon":"/favicon.svg",
 "appearance":{"default":"dark"},
 "fonts":{"family":"Inter"},
 "icons":{"library":"lucide"},
 "navbar":{"links":[{"type":"github","href":"https://github.com/mona-chen/raildock"},{"label":"Website","href":"/"}],"primary":{"type":"button","label":"API Reference","href":"/api-reference/"}},
 "search":{"prompt":"Search RailDock docs…"},
 "assistant":{"enabled":True},
 "knownPaths":["/","/api-reference/","/api-reference/*","/platform/","/platform/*","/manifests/","/manifests/*","/reliability/","/reliability/*","/self-hosting/","/self-hosting/*","/open-source/","/security/","/compare/"],
 "navigation":{"tabs":[
  {"tab":"Documentation","groups":[
   {"group":"Start here","pages":["index","getting-started/install","getting-started/first-project"]},
   {"group":"Core concepts","pages":["concepts/architecture","concepts/projects-environments","concepts/services"]},
   {"group":"Deploy applications","pages":["deploy/git","deploy/docker","deploy/deploy-sequence","deploy/domains-ssl","deploy/logs-terminal"]},
   {"group":"Declarative manifests","pages":["manifests/overview","manifests/reference","manifests/variables-links","manifests/reconciliation"]},
   {"group":"Data & recovery","pages":["data/databases","data/backups","data/pitr","data/destinations"]},
   {"group":"Operate RailDock","pages":["operate/server-provisioning","operate/networking","operate/external-proxy","operate/metrics"]},
   {"group":"Teams & integrations","pages":["teams/organizations-rbac","integrations/github"]},
   {"group":"API & security","pages":["api/overview","api/authentication","security/data-safety"]},
   {"group":"Help","pages":["troubleshooting"]}
  ]},
  {"tab":"API Reference","href":"/api-reference/"},
  {"tab":"GitHub","href":"https://github.com/mona-chen/raildock"}
 ],"global":{"anchors":[{"anchor":"RailDock home","href":"/","icon":"house"}]}}
}
(DOCS/'docs.json').write_text(json.dumps(nav,indent=2)+"\n")

pages={
'index.mdx':'''---\ntitle: RailDock documentation\ndescription: Deploy applications and databases to servers you control with RailDock.\n---\n\n# RailDock documentation\n\nRailDock is a self-hosted platform for deploying and operating applications and databases on infrastructure you control. It combines a web control plane, an HTTP API, declarative project manifests, an SSH-driven deployment engine, project-scoped networking, and data-safety workflows.\n\n## Where to begin\n\n- **New installation:** follow [Install RailDock](/getting-started/install).\n- **First workload:** create a project with [Your first project](/getting-started/first-project).\n- **Understand the system:** read [Architecture](/concepts/architecture).\n- **Manage state from a repository:** start with [Declarative manifests](/manifests/overview).\n- **Automate the control plane:** read the [API overview](/api/overview), then open the [interactive API reference](/api-reference/).\n\n## Product model\n\nA **server** is an execution target. A **project** groups related workloads. An **environment** gives a project an isolated desired state. A **service** is an application or datastore. RailDock connects these concepts to deployment jobs, private networking, domains, variables, backups, activity, and organization access.\n\n```text\nOrganization\n├── Servers\n├── Git sources\n├── Backup destinations\n└── Projects\n    └── Environments\n        ├── Application services\n        └── Datastore services\n```\n\n## Current scope\n\nRailDock can manage multiple servers, but a single project currently lives on one server. Preview environments, password reset, and an advanced write-capable database query console are not currently built in. The data browser is read-only.\n''',
'getting-started/install.mdx':'''---\ntitle: Install RailDock\ndescription: Bootstrap RailDock and its local deployment target on a Linux server.\n---\n\n# Install RailDock\n\nThe standard installer is the shortest path to a working RailDock control plane. It checks the host, installs or validates Docker and Dokku, creates RailDock's SSH identity and application secrets, starts the RailDock container, and creates the local server record.\n\n## Requirements\n\nUse a Linux host you administer and make sure RailDock's dashboard port is available. The standard setup serves the dashboard on **port 8888**.\n\n## Run the installer\n\n```bash\ncurl -sSL https://raw.githubusercontent.com/mona-chen/raildock/main/install.sh | bash\n```\n\nAfter installation, open:\n\n```text\nhttp://YOUR_SERVER_IP:8888\n```\n\nComplete the initial account setup, then validate the pre-created **Local Dokku** server.\n\n## Back up the control-plane secrets\n\nKeep recoverable copies of the generated `.env` and `backend/config/master.key` in your normal secrets/backup system. Do not commit them to source control. These files are part of RailDock's control-plane recovery material.\n\n## Next steps\n\n1. Read [Your first project](/getting-started/first-project).\n2. Configure a production hostname and TLS strategy.\n3. Add a remote server if the control plane should manage workloads elsewhere.\n4. Configure organization-level backup destinations before treating production data as protected.\n''',
'getting-started/first-project.mdx':'''---\ntitle: Your first project\ndescription: Create a project, add a service, configure a domain, and deploy it.\n---\n\n# Your first project\n\nA RailDock project is the operational boundary for related services. Services in a project can share an isolated network, reference one another, and participate in project-level deploy and lifecycle actions.\n\n## 1. Create a project\n\nCreate the project in the UI or through `POST /api/projects`. Assign the server that should run the project's workloads.\n\n## 2. Add an application service\n\nChoose a Git repository or Docker image. For an application service, configure the values that apply to the source: branch, root directory, builder, start command, exposed port, and auto-deploy preference.\n\n## 3. Add environment variables\n\nUse service variables for configuration specific to one workload. Use project shared variables when several services need the same value. For relationships to datastores or sibling services, prefer explicit service links and cross-service references where available.\n\n## 4. Deploy\n\nDeploy the service directly, or use the project-wide deployment action when you want RailDock to resolve dependencies and deploy the service graph in topological order.\n\n## 5. Watch the result\n\nFollow deployment state and logs. After the process is healthy, add a domain and validate the route.\n\n## Next\n\n- [Git deployments](/deploy/git)\n- [Docker image deployments](/deploy/docker)\n- [Domains and TLS](/deploy/domains-ssl)\n- [Deployment sequencing](/deploy/deploy-sequence)\n''',
'concepts/architecture.mdx':'''---\ntitle: Architecture\ndescription: Understand the RailDock control plane, deployment engine, jobs, realtime channels, and server runtime.\n---\n\n# Architecture\n\nRailDock separates **control-plane state** from **workload execution**. The web application models projects, services, organizations, manifests, and recovery configuration. Host mutations are delegated to execution engines that connect to servers over SSH.\n\n```text\nBrowser\n  ├── /       React frontend\n  ├── /api    Rails API\n  └── /cable  Action Cable\n              │\n              ▼\n        Rails control plane\n        ├── background jobs\n        ├── manifest reconciler\n        ├── DokkuEngine ── SSH ──> Dokku host\n        └── HostEngine  ── SSH ──> Linux host\n```\n\n## Production process\n\nThe application is packaged as a single Docker image with nginx, Puma, and background workers supervised together. The React frontend talks to same-origin `/api` endpoints and `/cable` realtime channels.\n\n## Key backend responsibilities\n\n- **Manifest parser / reconciler:** converts a declared desired state into a validated plan.\n- **Deployment sequence jobs:** order dependent services before dispatching service deployments.\n- **Deployment jobs:** execute individual lifecycle transitions.\n- **Project network manager:** creates and validates isolated Docker networking for a project.\n- **Proxy configuration:** generates external proxy state and Traefik labels where applicable.\n- **Recovery jobs:** handle scheduled backup, PITR, snapshot, and drill workflows.\n\n## Server boundary\n\nA RailDock server record contains the connectivity and provisioning context needed to operate a deployment target. A control plane may manage several servers, but one project currently belongs to one server.\n''',
'concepts/projects-environments.mdx':'''---\ntitle: Projects and environments\ndescription: How RailDock groups workloads and isolates desired state.\n---\n\n# Projects and environments\n\nProjects group services that should be operated as one application boundary. Environments let that project hold distinct service state without mixing configuration.\n\n## Project-level operations\n\nThe API exposes project activity, shared variables, deploy-all, cancel-deployments, restart-all, and stop-all operations. Deploy-all resolves service dependencies before execution.\n\n## Environment lifecycle\n\nEnvironments can be created, updated, removed, duplicated, previewed for synchronization, and synchronized. Use environments to keep distinct desired states explicit instead of encoding deployment stage only in ad-hoc variable names.\n\n## Server placement\n\nA project is assigned to a server. RailDock can manage multiple servers from one control plane, but does not currently schedule a single project across multiple hosts.\n''',
'concepts/services.mdx':'''---\ntitle: Services\ndescription: Application and datastore service lifecycle in RailDock.\n---\n\n# Services\n\nA service is the main unit RailDock deploys and operates. Application services can point at Git source or container images. Datastore services use type-specific lifecycle and recovery operations.\n\n## Common application settings\n\nThe current service model includes values such as name, service type/subtype, builder, Git repository, branch, version, port, Docker image, auto-deploy, root directory, start command, maintenance mode, restart policy, external networks, and configuration overrides.\n\n## Lifecycle actions\n\nDepending on service type, actions include deploy, rollback, scale, start, stop, restart, rebuild, run command, enter/terminal, lock/unlock, generate domain, and environment repair. Datastore services expose additional backup and recovery paths.\n\n## Locking\n\nUse service locking when an operational workflow should prevent casual lifecycle changes. The API exposes explicit lock, unlock, and lock-state operations.\n''',
'deploy/git.mdx':'''---\ntitle: Deploy from Git\ndescription: Configure source-backed services in RailDock.\n---\n\n# Deploy from Git\n\nConnect a repository-backed service when RailDock should build from source. Configure the repository, branch, optional root directory, builder, start command, port, and automatic-deploy preference.\n\n## Organization Git sources\n\nOrganizations can hold Git-source integrations. The API exposes repository, branch, and directory discovery endpoints for supported sources. RailDock also includes GitHub App installation and webhook flows.\n\n## Deployment path\n\nA deploy request creates deployment state and dispatches background execution. Follow the service deployment list and logs instead of assuming a successful request means the workload is already healthy.\n\n## Monorepos\n\nSet `root_directory` for services that should build from a subdirectory. Keep application-specific build instructions close to that service rather than duplicating monorepo logic in external deploy scripts.\n''',
'deploy/docker.mdx':'''---\ntitle: Deploy a Docker image\ndescription: Run image-backed services without rebuilding source in RailDock.\n---\n\n# Deploy a Docker image\n\nSet a service's Docker image when the artifact is already built and RailDock should operate the runtime lifecycle rather than build the source itself.\n\n## Image changes and desired state\n\nImage identity is build-sensitive state. When a declarative sync changes the image, RailDock can classify that delta as requiring a redeploy rather than treating it like an environment-only reconfiguration.\n\n## Imported workloads\n\nServer resources include Docker import workflows. Use these paths when bringing an existing host workload under RailDock rather than recreating everything manually. Review imported configuration before treating it as fully managed state.\n''',
'deploy/deploy-sequence.mdx':'''---\ntitle: Deployment sequencing\ndescription: How RailDock orders dependent services during project-wide deployments.\n---\n\n# Deployment sequencing\n\nProject-wide deployment is dependency-aware. RailDock builds a service graph and uses topological ordering so prerequisites can be dispatched before services that depend on them.\n\n```text\npostgres ─┐\n          ├──> api ──> web\nredis ────┘\n```\n\n## Why ordering matters\n\nA service graph makes relationships explicit and lets RailDock avoid an arbitrary loop over service records. This is especially useful when applications consume connection data from declared datastore links.\n\n## Cancel and retry\n\nThe project API includes cancellation of active project deployments, while individual deployment resources expose cancellation as well. After a failed sequence, inspect the failing service logs and state before retrying the whole graph.\n''',
'deploy/domains-ssl.mdx':'''---\ntitle: Domains and TLS\ndescription: Route public traffic to RailDock services.\n---\n\n# Domains and TLS\n\nDomains are attached to services. Application services can create and delete domain records, and RailDock also exposes generated-domain and proxy configuration paths.\n\n## Before attaching a domain\n\n1. Confirm the service process is healthy.\n2. Confirm the expected application port is configured.\n3. Point DNS at the public ingress for the target server.\n4. Add the domain in RailDock.\n5. Validate the external route and TLS behavior.\n\n## External proxy mode\n\nRailDock includes external proxy configuration and Traefik label generation. If your environment already owns the edge proxy, read [External proxy mode](/operate/external-proxy) before assuming RailDock should replace it.\n''',
'deploy/logs-terminal.mdx':'''---\ntitle: Logs and terminal\ndescription: Observe services and run targeted commands through RailDock.\n---\n\n# Logs and terminal\n\nUse service logs to diagnose build, release, startup, and runtime failures. The service API also exposes run-command and terminal/enter operations for targeted inspection.\n\n## Prefer a narrow operation\n\nUse logs and metrics before opening a terminal. When a command is needed, run the smallest diagnostic action that answers the current question. Interactive shell access is powerful and should be treated as production access.\n\n## One-shot commands\n\n`POST .../run` requires a command. Use it for bounded administration or diagnosis and keep durable configuration in manifests, service configuration, or source control instead of shell history.\n''',
'manifests/overview.mdx':'''---\ntitle: Declarative manifests\ndescription: Reconcile project desired state from raildock.toml, railway.toml, or app.json.\n---\n\n# Declarative manifests\n\nRailDock supports repository-level manifests including `raildock.toml`, `railway.toml`, and `app.json`. A manifest describes project state that can be parsed, compared with current state, previewed, and applied.\n\n## Reconciliation flow\n\n```text\nmanifest → parse → validate → diff → plan → confirm risky removals → apply → status\n```\n\nRailDock stores the manifest content and format, tracks synchronization/application timestamps, and exposes drift information so automation does not have to infer whether declared and actual state still match.\n\n## Preview first\n\nTreat preview as part of the normal workflow. The apply endpoint may require explicit confirmation for planned removals, so a CI job should not assume every desired-state change is safe to apply unattended.\n''',
'manifests/reference.mdx':'''---\ntitle: Manifest reference\ndescription: Practical RailDock manifest structure and compatibility notes.\n---\n\n# Manifest reference\n\nThe repository currently recognizes three manifest families: `raildock.toml`, `railway.toml`, and `app.json`. Exact accepted fields depend on the parser version running in your RailDock release.\n\n## Service intent\n\nA service declaration can describe application or datastore identity, source/image information, runtime configuration, dependencies, and environment values.\n\n```toml\n[services.api]\nsource = "github:acme/api"\nbranch = "main"\nport = 3000\ndepends_on = ["postgres"]\n\n[services.api.env]\nDATABASE_URL = "${postgres.DATABASE_URL}"\n\n[services.postgres]\ntype = "postgres"\n```\n\n> The snippet illustrates the desired model. Before committing a production manifest, use RailDock's parser/preview in the release you run to validate the exact syntax and supported fields.\n\n## Compatibility files\n\n`railway.toml` and `app.json` support lets repositories carry configuration from adjacent deployment ecosystems, while `raildock.toml` is the natural place for RailDock-specific desired state.\n''',
'manifests/variables-links.mdx':'''---\ntitle: Variables, links, and dependencies\ndescription: Connect RailDock services without hard-coding private endpoints.\n---\n\n# Variables, links, and dependencies\n\nService links make application relationships part of the project model. Cross-service variable references let an application consume connection data exposed by another service without copying generated endpoints into several configuration screens.\n\n## Dependency graph\n\nWhen service A depends on service B, model that relationship explicitly. Project-wide deployment can then order B before A.\n\n## Shared variables\n\nProjects expose shared-variable operations for values used by several services. Keep secrets at the narrowest useful scope and avoid duplicating the same secret into unrelated services only for convenience.\n\n## Repairing environment state\n\nThe service API includes an environment-repair action. Use it when managed runtime variables have diverged from RailDock's expected state, after first understanding why the drift occurred.\n''',
'manifests/reconciliation.mdx':'''---\ntitle: Reconciliation and drift\ndescription: How RailDock plans and applies desired-state changes.\n---\n\n# Reconciliation and drift\n\nReconciliation compares the stored desired state with the actual RailDock model and builds targeted changes. It is not equivalent to redeploying every service on every edit.\n\n## Change severity\n\nConceptually, changes fall into operational classes:\n\n- **Reconfigure:** values that can be updated without rebuilding source.\n- **Restart:** runtime changes that require the process to restart.\n- **Redeploy:** source, image, or build-sensitive changes requiring a rebuild/release path.\n\n## Drift\n\nUse the manifest drift endpoint to surface divergence instead of silently treating the UI and repository as equally authoritative. Establish one operating rule for your team: either repository state is authoritative for managed fields, or UI changes must be folded back into the manifest before the next apply.\n\n## Removals\n\nAn apply can stop when the plan contains removals that need explicit confirmation. Automation should handle that state as a review gate, not bypass it generically.\n''',
'data/databases.mdx':'''---\ntitle: Databases\ndescription: Operate datastore services and inspect data in RailDock.\n---\n\n# Databases\n\nDatastores are services with type-specific lifecycle. The service API exposes database information, backups, snapshots, schedules, recovery configuration, and a read-only data browser.\n\n## Data browser\n\nThe browser exposes table and row inspection paths. It is intentionally not an advanced write-capable SQL console. Use your normal database tooling for complex administration and keep high-risk data mutations outside casual control-plane browsing.\n\n## Links to applications\n\nLink an application to its datastore and use generated connection data through managed variables where possible. This keeps topology visible to the platform and reduces hard-coded host/port configuration.\n''',
'data/backups.mdx':'''---\ntitle: Backups\ndescription: Create, schedule, download, restore, and remove service backups.\n---\n\n# Backups\n\nRailDock exposes on-demand backup, backup schedule, download, restore, and delete operations for supported services.\n\n## Recommended operating sequence\n\n1. Create an organization backup destination.\n2. Verify that destination from RailDock.\n3. Create a schedule for each production datastore that needs protection.\n4. Check that backups are actually completing.\n5. Run a recovery drill on a regular cadence.\n6. Document any service-specific restore caveats.\n\n## Do not confuse scheduling with recovery readiness\n\nA cron-like schedule proves that a job is configured, not that the archive is restorable. Verification and recovery drills close that gap.\n''',
'data/pitr.mdx':'''---\ntitle: Point-in-time recovery\ndescription: Configure and exercise PITR controls for supported RailDock datastores.\n---\n\n# Point-in-time recovery\n\nRailDock exposes PITR configuration and removal endpoints as part of the service recovery surface. PITR support and exact semantics depend on the datastore and recovery backend.\n\n## Before enabling PITR\n\n- Confirm the datastore type/version is supported by your RailDock release.\n- Configure and verify an appropriate recovery destination.\n- Confirm retention and storage expectations.\n- Run an isolated recovery drill before relying on PITR for production.\n\n## Recovery preferences\n\nService recovery preferences are separate from the base service record. Keep recovery policy explicit, review it after datastore upgrades, and include the recovery path in your operating runbook.\n''',
'data/destinations.mdx':'''---\ntitle: Backup destinations\ndescription: Configure and verify organization-level off-site recovery destinations.\n---\n\n# Backup destinations\n\nBackup destinations belong to the organization layer so several protected services can use centrally managed recovery storage. RailDock exposes create, update, delete, default-setting, and verification operations.\n\n## Verify immediately\n\nAfter adding credentials or destination configuration, use the verification endpoint before assigning critical backup schedules. A syntactically valid destination is not necessarily reachable or writable.\n\n## Credentials\n\nTreat destination credentials as production secrets. Restrict them to the minimum storage permissions needed for the backup/recovery workflow and rotate them according to your infrastructure policy.\n''',
'operate/server-provisioning.mdx':'''---\ntitle: Server provisioning\ndescription: Attach, test, provision, and validate RailDock execution targets.\n---\n\n# Server provisioning\n\nServers are RailDock's execution targets. The API exposes create/update/delete, connectivity test, provisioning, provisioning status, validation, host metrics, and network inspection.\n\n## Provisioning flow\n\n1. Create the server record with its connection information.\n2. Test connectivity.\n3. Start provisioning with the appropriate proxy mode and options.\n4. Follow provisioning status.\n5. Run validation and review detected runtime information.\n6. Assign a project only after the host is ready.\n\n## Validation data\n\nValidation can update detected server status, software version, OS information, uptime, proxy state, and public IP information. Treat validation as a current observation, not a permanent guarantee of host health.\n''',
'operate/networking.mdx':'''---\ntitle: Project networking\ndescription: Understand RailDock private service networking and DNS discovery.\n---\n\n# Project networking\n\nRailDock creates isolated Docker networks for projects and uses service discovery to keep private communication inside the project boundary. External networks can also be attached when a service needs an explicitly shared network.\n\n## Prefer private connectivity\n\nDo not publish a database merely so an application on the same project can reach it. Use the project network and service link model for east-west traffic, then expose only the public application surface that actually needs ingress.\n\n## Inspect host networks\n\nServer resources expose network inspection and validation. Use them when imported workloads, external proxying, or manual host changes have created unexpected connectivity.\n''',
'operate/external-proxy.mdx':'''---\ntitle: External proxy mode\ndescription: Integrate RailDock with an existing edge proxy.\n---\n\n# External proxy mode\n\nRailDock includes proxy configuration helpers and Traefik label generation for environments where the edge is managed separately from the control plane.\n\n## When to use it\n\nUse external proxy mode when your infrastructure already has a central ingress/TLS layer and RailDock should emit or cooperate with routing metadata instead of owning the complete edge path itself.\n\n## Verify the contract\n\nDocument which component owns DNS, certificates, ports, service discovery, and health checking. Split ownership is workable only when the boundary is explicit.\n''',
'operate/metrics.mdx':'''---\ntitle: Metrics and host health\ndescription: Inspect service and server resource signals through RailDock.\n---\n\n# Metrics and host health\n\nService resources expose current metrics and metrics history. Server resources expose host-level metrics gathered through the host engine, including common load, memory, and filesystem information.\n\n## Use metrics with logs\n\nMetrics tell you **that** resource behavior changed; logs often tell you **why**. During an incident, correlate deployment events, service metrics, server metrics, and runtime logs before making large configuration changes.\n\n## External observability\n\nRailDock's built-in signals are useful for operations but do not replace a dedicated long-retention metrics/logging stack when your reliability requirements call for one.\n''',
'teams/organizations-rbac.mdx':'''---\ntitle: Organizations and access\ndescription: Organize projects, servers, members, invitations, keys, sources, and backup destinations.\n---\n\n# Organizations and access\n\nOrganizations group shared operational resources. The current API includes organization projects, Git sources, members, invitations, deploy keys, servers/bootstrap information, backup destinations, and data-safety settings.\n\n## Members and invitations\n\nUse membership and invitation flows to grant human access instead of sharing one administrator credential. Keep roles aligned with the work people need to perform.\n\n## Deploy keys\n\nUse deploy keys for automation that should not depend on an interactive user's session. Rotate keys and remove them when the corresponding CI/CD integration or environment is retired.\n\n## Activity\n\nReview organization and project activity as part of incident diagnosis and change review. Operational history is most useful when shared accounts are avoided.\n''',
'integrations/github.mdx':'''---\ntitle: GitHub integration\ndescription: Connect repositories with RailDock GitHub App and webhook flows.\n---\n\n# GitHub integration\n\nRailDock includes GitHub App manifest/setup callbacks, installation handling, repository discovery, and webhook endpoints. Organization Git-source resources expose repositories, branches, and directories to the control plane.\n\n## Recommended setup\n\n1. Configure the RailDock GitHub App settings.\n2. Test the GitHub App configuration from administration settings.\n3. Install the app for the repositories RailDock needs.\n4. Add the resulting Git source to the organization.\n5. Select repositories from that source when configuring services.\n\n## Webhooks\n\nRailDock has deployment webhook endpoints, including service-specific webhook deployment. Keep webhook secrets and GitHub App credentials in the control-plane secret store, not in repository manifests.\n''',
'api/overview.mdx':'''---\ntitle: API overview\ndescription: Automate RailDock projects, services, manifests, servers, organizations, and recovery workflows.\n---\n\n# API overview\n\nRailDock exposes an HTTP API under `/api`. The current API is **not version-prefixed**, so clients should pin the RailDock release they test against and treat the interactive reference as release-coupled documentation.\n\n## Base URL\n\nFor a RailDock host at `https://raildock.example.com`, the API base is:\n\n```text\nhttps://raildock.example.com/api\n```\n\n## Health check\n\n```bash\ncurl https://raildock.example.com/api/health\n```\n\nThe health endpoint returns status and server time.\n\n## Authentication\n\nMost control-plane endpoints require a bearer JWT. Read [Authentication](/api/authentication).\n\n## Interactive reference\n\nOpen the [Scalar API Reference](/api-reference/) for endpoint discovery, schema inspection, and request examples.\n\n> The supplied OpenAPI document is a website/reference companion derived from the current route/controller research. Because the repository does not currently ship a canonical OpenAPI file, validate request bodies and responses against the RailDock release you deploy before generating a strict production SDK.\n''',
'api/authentication.mdx':'''---\ntitle: API authentication\ndescription: Authenticate to RailDock and use JWT bearer tokens.\n---\n\n# API authentication\n\nAuthenticate with the login endpoint, then pass the returned JWT in the `Authorization` header.\n\n## Login\n\n```bash\ncurl -X POST https://raildock.example.com/api/login \\\n  -H 'Content-Type: application/json' \\\n  -d '{"email":"operator@example.com","password":"..."}'\n```\n\nA successful response includes `token` and `user`.\n\n## Bearer requests\n\n```bash\ncurl https://raildock.example.com/api/me \\\n  -H "Authorization: Bearer $RAILDOCK_TOKEN"\n```\n\nThe backend verifies bearer JWTs using HS256 and resolves the current user before protected actions.\n\n## Token handling\n\nTreat the token as a credential with control-plane privileges. Do not place it in query strings, commit it to scripts, or write it into logs. For non-interactive automation, prefer the purpose-built key/deployment mechanisms available to your RailDock workflow rather than recycling a human session indefinitely.\n''',
'security/data-safety.mdx':'''---\ntitle: Data safety and destructive actions\ndescription: RailDock guardrails for deletion, backups, credentials, and recovery.\n---\n\n# Data safety and destructive actions\n\nRailDock makes several destructive paths explicit. Project and service deletion can require typed confirmation, and project deletion may return a precondition response when a snapshot/safety step is still required.\n\n## Treat the control plane as privileged infrastructure\n\nRailDock can mutate application, network, and datastore state on attached hosts. Protect the RailDock host, database, Rails master key, SSH material, Git integration credentials, backup destination credentials, and administrator sessions accordingly.\n\n## Before deleting production data\n\n1. Confirm the target name and environment.\n2. Review dependent services.\n3. Create or verify the required snapshot/backup.\n4. Confirm the recovery destination is reachable.\n5. Record the change in your normal change-management workflow.\n6. Only then submit the destructive confirmation.\n\n## Security documentation\n\nThis documentation describes visible product controls; it is not a security audit. A production project should also maintain a repository `SECURITY.md` with supported versions and a private disclosure path.\n''',
'troubleshooting.mdx':'''---\ntitle: Troubleshooting\ndescription: A disciplined workflow for diagnosing RailDock deployments and servers.\n---\n\n# Troubleshooting\n\nStart at the narrowest failing layer and move outward. Avoid reinstalling or rebuilding everything before you know which boundary is broken.\n\n## A service will not start\n\n1. Open the latest deployment and logs.\n2. Confirm source/image and expected start command.\n3. Confirm required environment variables exist.\n4. Check the configured exposed port.\n5. Check linked datastore health and project networking.\n6. Review restart policy and container state.\n\n## A domain does not route\n\n1. Confirm the service itself is healthy privately.\n2. Check DNS against the server's public ingress.\n3. Check domain configuration on the service.\n4. Inspect proxy mode and generated configuration.\n5. Validate the server and relevant networks.\n\n## A server fails provisioning\n\nUse the server connectivity test first, then review provisioning status. Confirm SSH access, supported Linux environment, Docker/Dokku state, and proxy-mode assumptions.\n\n## A manifest will not apply\n\nRun preview/sync-plan and inspect validation errors. Check whether the plan contains removals that require confirmation, then inspect manifest status and drift.\n\n## Recovery concerns\n\nDo not attempt a destructive restore blindly. Verify the destination, identify the backup/PITR target, and use an isolated recovery drill when possible.\n\n## Report a bug\n\nWhen opening a GitHub issue, include the RailDock release/commit, affected service type, sanitized logs, the action you attempted, and the smallest reproducible sequence. Never paste secrets.\n'''
}
for rel,txt in pages.items():
    p=DOCS/rel;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(txt.strip()+"\n")
print(f'Wrote {len(pages)} Holocron MDX pages')
